### ISSUE TITLE
Deprecate this project when an official replacement is ready

### ISSUE THREAD

**Issue by ryanatkn** [ryanatkn/awesome-svelte-resources#18]
One day [a proposed official website](https://github.com/sveltejs/svelte/issues/1070) is probably going to make this project obsolete. Until then, it seems like a helpful community-building thing to maintain. This project is a single markdown file, which is a seriously lacking UX, but it's a bridge to better places.

Currently the Svelte team maintains a more focused list of **[integrations](https://github.com/sveltejs/integrations)**. This project points to the official integrations list in multiple places and mostly avoids duplicating its role, but there's no official list of other community resources.

When an official replacement arrives, this project will be sunset. :wave::city_sunset:

**Comment by sw-yx** [comment]
hey ryan,

this is the best awesome svelte list out there!

we just got going with https://github.com/sveltejs/community/ and wonder if you'd like to merge. you'd be a maintainer, but also have me and kev to share the maintenance burden. 

would also close https://github.com/ryanatkn/awesome-svelte-resources/issues/19

**Comment by ryanatkn** [comment]
Hey, that's fantastic, I'd love to merge. Let me know what I can do to help proceed. I started watching sveltejs/community to keep up and I'll be around on Discord.

**Comment by pngwn** [comment]
Just saw this after my [previous comment](https://github.com/sveltejs/integrations/issues/21) in [`sveltejs/integrations`](https://github.com/sveltejs/integrations) I'm not 100% convinced that a resource-list should live in the community repo, I guess we can discuss where makes the most sense.

**Comment by sw-yx** [comment]
yeah. to be clear i'm kinda winging it, i dont have strong opinions on what to do either. if you want to take a call, make a decision, i dont know whats best

**Comment by pngwn** [comment]
Nor me! I wouldn’t worry about it too much right now, we can think about it and experiment with it and see if a wave of clarity hits us. 

It might help us to try thinking of the big picture a little. What would it all look like if we implemented everything we wanted to? Component marketplace, cookbook, events, resource lists, shareable repls , as well everything we currently have. 

Where should it all live? What would be the best way to maintain it? How complex or simple do we want these these features, sections or mini sites to be?

I don’t know if this is the best way to look at it but it’s another perspective and might help avoid causing problems down the line. I’ll try to think about it a little over the next week although to have quite a bit on. 

If you have any ideas or suggestions don’t hesitate to share them either in issues or privately if you prefer. Likewise we are all very appreciative of the efforts that are being put in, both here and elsewhere, Svelte is nothing  without it’s community  so this is all very cool to see.

**Comment by arxpoetica** [comment]
Apologize for the noise, but leaving this here since it's semi-related, and I want to easily find the cross-ref later: https://github.com/sveltejs/svelte/issues/1070
