### ISSUE TITLE
Consider renaming the repo

### ISSUE THREAD

**Issue by ryanatkn** [ryanatkn/awesome-svelte-resources#19]
### Why rename

- the quality bar is not _"awesome or better"_ - it's not an _"everything"_ list either though - I tend to add _"useful and interesting things of at least decent quality"_
- I have no plans to submit to the [official awesome meta list](https://github.com/sindresorhus/awesome) - the goals here are a little different (see [the plan for deprecation](https://github.com/ryanatkn/awesome-svelte-resources/issues/18))
- confusion with [CalvinWalzel/awesome-svelte](https://github.com/CalvinWalzel/awesome-svelte) - I knew about it when I started this project, but its maintenance didn't appear to match the pace of community activity after Svelte 3 was released
- the _awesome_ convention is ["incredibly grating" to Svelte core contributors](https://github.com/sveltejs/svelte/pull/2436#issuecomment-484496473) (eep lol)

### Why keep the current name

- _awesome_ has significant recognition among programmers, or at least GitHub users, so for many people it's descriptive and searchable
- the "-resources" suffix might be enough to differentiate it from CalvinWalzel/awesome-svelte
- renaming might be confusing for some people

### Proposed names

- `useful-svelte-resources` - simple and to the point, and the more I look at the word "useful" the more I like it
- `bloated-svelte` - the original tongue-in-cheek name, still redirects from [ryanatkn/bloated-svelte](https://github.com/ryanatkn/bloated-svelte) to this project - it isn't descriptive and might confuse some people
- something else?

**Comment by thompcd** [comment]
I am considering forking this repo to create a sapper version. Would you be alright with this? If so, have you landed on a name here? I don't want to just straight copy necessarily, but I thought it would be neat to mimic it initially and treat it like a sibling resource.

**Comment by ryanatkn** [comment]
Cool, for sure, fork away! I've seen a lot of demand for a Sapper version on Discord. It'll be nice to have a similar project to learn from to help improve this one. I'd be interested to hear any design thoughts that come up.

For the name, the only feedback I've seen is that "awesome" helps people find and understand the project. Those seem like good things to optimize. Do you agree with just keeping it how it is? I'm not sure the resources suffix helps at all, so you may want to consider dropping it, but I also like the idea of having them mirror each other as sibling projects.

**Comment by ryanatkn** [comment]
Update: looks like the [sveltejs/community](https://github.com/sveltejs/community) is going to take on the aggregation role as brought up in #18. It's also going to include Sapper resources, and I'm sure they would welcome help.

**Comment by ryanatkn** [comment]
A clarification - sveltejs/community may not be the actual repo, it's yet to be decided if resources should live as a separate site.
