### ISSUE TITLE
official russian website

### ISSUE THREAD

**Issue by AlexxNB** [ryanatkn/awesome-svelte-resources#21]
I was going to make PR, but not shure about right placement.
I'm maintainer of the official russian website - https://ru.svelte.dev.  It is a translated copy of the official website. 
Also we have a Github-repo, where anybody can contribute for better translation - https://github.com/AlexxNB/svelte3-translation-ru . 

Please add it to the official links or make new section like 'International links'.

**Comment by ryanatkn** [comment]
Thank you for the submission. The above commit seems like a good starting point but I think there's room for improvement. I'd be happy to get any feedback.

**Comment by AlexxNB** [comment]
Great, thank you!
