### ISSUE TITLE
Add another router

### ISSUE THREAD

**Issue by lyohaplotinka** [ryanatkn/awesome-svelte-resources#3]
Hello there! Thanks for this list, it is really awesome!

It would be great if you add my router: [Svelte Easyroute](https://github.com/lyohaplotinka/svelte-easyroute). 
It has vue-syntax and some powerful tools.
Thanks!

**Comment by ryanatkn** [comment]
Looks good, thank you! Added in [this commit](https://github.com/ryanatkn/awesome-svelte-resources/commit/54a128c3191c18065c6e8a5c21ecfe7cb944b1c2).

**Comment by lyohaplotinka** [comment]
@ryanatkn thanks again!
