### ISSUE TITLE
add Calendar Component https://github.com/keithj2780/svelte-calendar

### ISSUE THREAD

**Issue by keithj2780** [ryanatkn/awesome-svelte-resources#33]
REPL at https://svelte.dev/repl/5aa7d011c2104b0c8906248f66da22ea?version=3.12.1

**Comment by ryanatkn** [comment]
Looks great, thank you for sharing!

It appears the days are off - today is Sunday Nov 10 2019, but the screenshot and demo show the 10th as a Saturday.

Do you plan to publish to npm? There's already a `svelte-calendar` but you could namespace it under a user to keep the name. I don't know all of the best practices (except [the "svelte" field in package.json](https://github.com/6eDesign/svelte-calendar/blob/master/package.json#L3)) but there are lots of examples to follow.

**Comment by ryanatkn** [comment]
Added to the list. If you publish to npm I'll update the formatting - in the successor to this project, [sveltejs/community](https://github.com/sveltejs/community), it'll link to the npm project and probably display stats in the future.

**Comment by ryanatkn** [comment]
This project is now deprecated - please direct any followups to [sveltejs/community](https://github.com/sveltejs/community).
