### ISSUE TITLE
Add svelte-typewriter

### ISSUE THREAD

**Issue by henriquehbr** [ryanatkn/awesome-svelte-resources#34]
[`svelte-typewriter`](https://github.com/henriquehbr/svelte-typewriter) is a simple and reusable typewriter effect for Svelte applications

**Demo:** https://svelte.dev/repl/9dfb73bfa9b34aeea4740fa23f5cde8a?version=3.14.1

**Comment by ryanatkn** [comment]
Nice thank you!
