### ISSUE TITLE
Anything like these for Svelte?

### ISSUE THREAD

**Issue by frederikhors** [ryanatkn/awesome-svelte-resources#43]
- https://github.com/vazco/uniforms

- https://github.com/frontier-forms/frontier-forms

**Comment by ryanatkn** [comment]
I don't know of any unfortunately. They look super useful. Maybe ask on Discord or over at [sveltejs/community](https://github.com/sveltejs/community)?

**Comment by ryanatkn** [comment]
This project is now deprecated - please direct any followups to [sveltejs/community](https://github.com/sveltejs/community).
