### ISSUE TITLE
Please add the Parcel template.

### ISSUE THREAD

**Issue by hmmhmmhm** [ryanatkn/awesome-svelte-resources#44]
https://github.com/hmmhmmhm/svelte-template
https://github.com/hmmhmmhm/svelte-spa-template

Happy 2020 New Year!

I have developed and provided `Parcel` + `Svelte v3` +
`Typescript` + `SCSS` + `Autoprifixer` + `Prettier` templates.

My boilerplate can fully activate ts intellisense even in
`.svelte` file and ie8 is also compatible with parcel and autoprefixer. (es3 Conversion)

I didn't know what order of criteria to modify md so I couldn't send PR.
Can anyone add my template in list?

**Comment by ryanatkn** [comment]
Looks good, thanks! I added them to the list. Also check out [sveltejs/community](https://github.com/sveltejs/community) if you haven't seen it yet.
